Python 2.7:
  script:
  - py_version=2.7
  - EXTRA_INSTALL="numpy scipy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.7
  - gfortran
  except:
  - tags

Python 3.5:
  script:
  - py_version=3.5
  - EXTRA_INSTALL="numpy scipy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python3.5
  - gfortran
  except:
  - tags

Python 3.5 Examples:
  script:
  - py_version=3.5
  - EXTRA_INSTALL="numpy scipy matplotlib"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-py-project-and-run-examples.sh
  - ". ./build-py-project-and-run-examples.sh"
  tags:
  - python3.5
  except:
  - tags

Python 2.6:
  script:
  - py_version=2.6
  - EXTRA_INSTALL="numpy scipy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-and-test-py-project.sh
  - ". ./build-and-test-py-project.sh"
  tags:
  - python2.6
  - gfortran
  except:
  - tags

Documentation:
  script:
  - EXTRA_INSTALL="numpy"
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/build-docs.sh
  - ". ./build-docs.sh"
  tags:
  - python3.5
  only:
  - master

Flake8:
  script:
  - curl -L -O -k https://gitlab.tiker.net/inducer/ci-support/raw/master/prepare-and-run-flake8.sh
  - ". ./prepare-and-run-flake8.sh leap test"
  tags:
  - python3.5
  except:
  - tags
